[variables]
PUPPETEER_SKIP_DOWNLOAD = "1"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["echo 'Deferring install to build phase'"]

[phases.build]
cmds = ["cd frontend && npm install", "cd frontend && npm run build"]

[start]
cmd = "cd frontend && npx serve -s dist -l $PORT"
